<?php

/**
 * This is the model base class for the table "tbl_post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TblPost".
 *
 * Columns in table "tbl_post" available as properties of the model,
 * followed by relations of table "tbl_post" available as properties of the model.
 *
 * @property integer $post_id
 * @property integer $post_author
 * @property string $post_date
 * @property string $post_content
 * @property integer $post_status
 * @property string $post_title
 * @property string $post_modified_date
 * @property integer $comment_count
 * @property integer $post_rate
 * @property integer $post_comment_open
 * @property string $post_type
 *
 * @property TblComment $post
 * @property TblUser $postAuthor
 * @property TblUser $tblUser
 */
abstract class BaseTblPost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TblPost|TblPosts', $n);
	}

	public static function representingColumn() {
		return 'post_date';
	}

	public function rules() {
		return array(
			array('post_author, post_status, comment_count, post_rate, post_comment_open', 'numerical', 'integerOnly'=>true),
			array('post_type', 'length', 'max'=>100),
			array('post_date, post_content, post_title, post_modified_date', 'safe'),
			array('post_author, post_date, post_content, post_status, post_title, post_modified_date, comment_count, post_rate, post_comment_open, post_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('post_id, post_author, post_date, post_content, post_status, post_title, post_modified_date, comment_count, post_rate, post_comment_open, post_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'post' => array(self::BELONGS_TO, 'TblComment', 'post_id'),
			'postAuthor' => array(self::BELONGS_TO, 'TblUser', 'post_author'),
			'tblUser' => array(self::HAS_ONE, 'TblUser', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'post_id' => null,
			'post_author' => null,
			'post_date' => Yii::t('app', 'Post Date'),
			'post_content' => Yii::t('app', 'Post Content'),
			'post_status' => Yii::t('app', 'Post Status'),
			'post_title' => Yii::t('app', 'Post Title'),
			'post_modified_date' => Yii::t('app', 'Post Modified Date'),
			'comment_count' => Yii::t('app', 'Comment Count'),
			'post_rate' => Yii::t('app', 'Post Rate'),
			'post_comment_open' => Yii::t('app', 'Post Comment Open'),
			'post_type' => Yii::t('app', 'Post Type'),
			'post' => null,
			'postAuthor' => null,
			'tblUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('post_author', $this->post_author);
		$criteria->compare('post_date', $this->post_date, true);
		$criteria->compare('post_content', $this->post_content, true);
		$criteria->compare('post_status', $this->post_status);
		$criteria->compare('post_title', $this->post_title, true);
		$criteria->compare('post_modified_date', $this->post_modified_date, true);
		$criteria->compare('comment_count', $this->comment_count);
		$criteria->compare('post_rate', $this->post_rate);
		$criteria->compare('post_comment_open', $this->post_comment_open);
		$criteria->compare('post_type', $this->post_type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}