<?php

/**
 * This is the model base class for the table "tbl_teacher".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TblTeacher".
 *
 * Columns in table "tbl_teacher" available as properties of the model,
 * followed by relations of table "tbl_teacher" available as properties of the model.
 *
 * @property integer $teacher_id
 * @property string $teacher_name
 * @property integer $teacher_faculty
 * @property string $teacher_subject
 * @property string $teacher_profile
 * @property integer $teacher_rate
 * @property string $teacher_url
 * @property string $teacher_comment
 *
 * @property TblFaculty $teacherFaculty
 */
abstract class BaseTblTeacher extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_teacher';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TblTeacher|TblTeachers', $n);
	}

	public static function representingColumn() {
		return 'teacher_name';
	}

	public function rules() {
		return array(
			array('teacher_faculty, teacher_rate', 'numerical', 'integerOnly'=>true),
			array('teacher_name, teacher_subject, teacher_url', 'length', 'max'=>100),
			array('teacher_profile, teacher_comment', 'safe'),
			array('teacher_name, teacher_faculty, teacher_subject, teacher_profile, teacher_rate, teacher_url, teacher_comment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('teacher_id, teacher_name, teacher_faculty, teacher_subject, teacher_profile, teacher_rate, teacher_url, teacher_comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'teacherFaculty' => array(self::BELONGS_TO, 'TblFaculty', 'teacher_faculty'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'teacher_id' => Yii::t('app', 'Teacher'),
			'teacher_name' => Yii::t('app', 'Teacher Name'),
			'teacher_faculty' => null,
			'teacher_subject' => Yii::t('app', 'Teacher Subject'),
			'teacher_profile' => Yii::t('app', 'Teacher Profile'),
			'teacher_rate' => Yii::t('app', 'Teacher Rate'),
			'teacher_url' => Yii::t('app', 'Teacher Url'),
			'teacher_comment' => Yii::t('app', 'Teacher Comment'),
			'teacherFaculty' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('teacher_id', $this->teacher_id);
		$criteria->compare('teacher_name', $this->teacher_name, true);
		$criteria->compare('teacher_faculty', $this->teacher_faculty);
		$criteria->compare('teacher_subject', $this->teacher_subject, true);
		$criteria->compare('teacher_profile', $this->teacher_profile, true);
		$criteria->compare('teacher_rate', $this->teacher_rate);
		$criteria->compare('teacher_url', $this->teacher_url, true);
		$criteria->compare('teacher_comment', $this->teacher_comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}